// Image manifest - maps image names to their available sizes
// This file is auto-generated by scripts/generateImageManifest.js
// Run: npm run generate:manifest to regenerate

export const imageManifest = {
  "apple": [
    320
  ],
  "google": [
    320
  ],
  "img5": [
    320,
    640,
    768,
    1024,
    1280
  ],
  "man": [
    320
  ],
  "phones": [
    320,
    640,
    768,
    1024,
    1280
  ],
  "pickup": [
    320,
    640,
    768,
    1024,
    1280
  ],
  "pricing": [
    320,
    640,
    768,
    1024,
    1280
  ],
  "service": [
    320,
    640,
    768,
    1024
  ],
  "services_2": [
    320
  ],
  "services_3": [
    320
  ],
  "services_4": [
    320
  ],
  "services_5": [
    320
  ],
  "services_6": [
    320
  ],
  "step1": [
    320
  ],
  "step2": [
    320
  ],
  "step3": [
    320,
    640,
    768
  ],
  "step4": [
    320,
    640,
    768
  ],
  "truck": [
    320,
    640
  ],
  "verfied": [
    320,
    640,
    768
  ],
  "whyus": [
    320,
    640,
    768,
    1024,
    1280
  ]
};

/**
 * Get available sizes for an image
 * @param {string} imageName - Base name of the image (without extension)
 * @returns {number[]} Array of available widths
 */
export function getAvailableSizes(imageName) {
  return imageManifest[imageName] || [];
}
