import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

console.log('📝 Generating Image Manifest for ResponsiveAssetImage\n');

// Read the optimization manifest
const manifestPath = path.join(__dirname, '../public/assets-optimized/manifest.json');
const outputPath = path.join(__dirname, '../src/utils/imageManifest.js');

try {
  const manifestData = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  
  // Build the image manifest object
  const imageManifest = {};
  
  manifestData.images.forEach(img => {
    // Extract base name without extension
    const baseName = img.original.replace(/\.[^/.]+$/, '');
    
    // Get available widths
    const availableSizes = img.responsive.map(resp => resp.width);
    
    imageManifest[baseName] = availableSizes;
  });
  
  // Generate the JavaScript file content
  const fileContent = `// Image manifest - maps image names to their available sizes
// This file is auto-generated by scripts/generateImageManifest.js
// Run: npm run generate:manifest to regenerate

export const imageManifest = ${JSON.stringify(imageManifest, null, 2)};

/**
 * Get available sizes for an image
 * @param {string} imageName - Base name of the image (without extension)
 * @returns {number[]} Array of available widths
 */
export function getAvailableSizes(imageName) {
  return imageManifest[imageName] || [];
}
`;
  
  // Write the file
  fs.writeFileSync(outputPath, fileContent);
  
  console.log('✅ Image manifest generated successfully!');
  console.log(`📄 Output: ${outputPath}`);
  console.log(`\n📊 Images processed: ${Object.keys(imageManifest).length}`);
  console.log('\nAvailable sizes per image:');
  
  Object.entries(imageManifest).forEach(([name, sizes]) => {
    console.log(`  ${name}: [${sizes.join(', ')}]`);
  });
  
} catch (error) {
  console.error('❌ Error generating manifest:', error.message);
  process.exit(1);
}
